name: Test Semantic Release Version

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read


jobs:
  test-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: codfish/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - run: |
        echo $RELEASE_VERSION
        echo $RELEASE_MAJOR
        echo $RELEASE_MINOR
        echo $RELEASE_PATCH
