name: Deploy on PR Approved

on:
  pull_request_review:
    types: [submitted]

jobs:
  deploy-if-approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Extract PR info
        id: pr
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Repo: ${{ github.repository }}"
          echo "ref=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
